In [7]:
#  Loading Required Libraries and Data 

import pandas as pd
from IPython.display import display

# file path
file_path = "../data/Common Data Warehouse-Orginal.xlsx"


xls = pd.ExcelFile(file_path)

customer_df = xls.parse("Customer")  #  Rating Score and Country

#  Identify High-Risk Customers (Lowest Ratings 0, 1, 2, 3)


def is_high_risk(score):
    """If the customer has a high-risk rating (0, 1, 2)."""
    score = str(score)  
    # Extracting numeric part 
    numeric_part = ''.join(filter(str.isdigit, score))  
    if numeric_part in ["0", "1", "2"]:  # Checking if the extracted number is in high-risk range
        return True
    return False

# Creating a "High Risk" column
customer_df["High Risk"] = customer_df["Rating Score"].apply(is_high_risk)

#  Identifying Correct Country Column
possible_country_columns = [col for col in customer_df.columns if "country" in col.lower()]
if possible_country_columns:
    country_column = possible_country_columns[0]  # Use the first detected country column
else:
    raise KeyError("Column 'Country' not found in dataset.")

#  Counting High-Risk Customers by Country
high_risk_customers_df = customer_df[customer_df["High Risk"] == True]

# Grouping by the country column and high-risk customers
high_risk_by_country = high_risk_customers_df.groupby(country_column).agg(
    High_Risk_Count=("Customer ID", "count")
)

# Sorting by highest number of high-risk customers
high_risk_by_country = high_risk_by_country.sort_values(by="High_Risk_Count", ascending=False)

#  Results
print("ðŸ”¹ High-Risk Customers by Country:")
display(high_risk_by_country)

# Save Results to Excel
output_file_path = "High_Risk_Customers_By_Country.xlsx"
high_risk_by_country.to_excel(output_file_path, index=False)

print(f"Results saved successfully to: {output_file_path}")

ðŸ”¹ High-Risk Customers by Country:

         High_Risk_Count
Country
DK                   393
NO                   122
LR                    39
FI                    26
SE                    10
BM                     6
CY                     4
CH                     3
FR                     3
GH                     3
HK                     2
NL                     2
IT                     2
GB                     2
DE                     2
AO                     1
BR                     1
BE                     1
CN                     1
CL                     1
JE                     1
EG                     1
MH                     1
LV                     1
KY                     1
PL                     1

Results saved successfully to: High_Risk_Customers_By_Country.xlsx